#!/bin/bash
# Script:                       Ops 301 Ops Chall 03
# Author:                       Courtney Johnson    
# Date of latest revision:      09/01/2022
# Purpose:                      Conditionals in Menu Settings

#Create a bash script that launches a menu system with the following options:
#Hello world (prints “Hello world!” to the screen)
# echo "Hello World"
# read n

# #Ping self (pings this computer’s loopback address)
# $ ping localhost

# #IP info (print the network adapter information for this computer)
#ip a
# #Exit


#Next, the user input should be requested.
#The program should next use a conditional statement to evaluate the user’s input, then act according to what the user selected.
#Use a loop to bring up the menu again after the request has been executed.


echo "Option 1 Print Hello World
Option 2 Ping Self
Option 3 Print Network Adapter Infomation 
Option 4 Exit"

read choice

if [[ $choice == 1 ]]; then
    echo hello world
elif [[ $choice == 2 ]]; then
    ping localhost
elif [[ $choice == 3 ]]; then
    ip a
elif [[ $choice == 4 ]]; then
    exit
else
    echo "invalid input!"
fi
